steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/slc-air-quality-424017/aqi-predictor", "."]

  # Step 2: Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/slc-air-quality-424017/aqi-predictor"]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aqi-predictor",
        "--image",
        "gcr.io/slc-air-quality-424017/aqi-predictor",
        "--region",
        "us-west2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/slc-air-quality-424017/aqi-predictor"
