steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/continual-modem-424017-r2/slc-air-quality/aqi-predictor",
        ".",
      ]

  # Step 2: Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/continual-modem-424017-r2/slc-air-quality/aqi-predictor",
      ]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aqi-predictor",
        "--image",
        "us-west2-docker.pkg.dev/continual-modem-424017-r2/slc-air-quality/aqi-predictor",
        "--region",
        "us-west2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "us-west2-docker.pkg.dev/continual-modem-424017-r2/slc-air-quality/aqi-predictor"
